spring:
      datasource :
            url      : jdbc:mysql://localhost:3306/friendMgmt
            username : root
            password : 123456
      jpa :
           properties.hibernate.dialect : org.hibernate.dialect.MySQL5InnoDBDialect
           hibernate.ddl-auto : update
           hibernate.show_sql  : true
server :
    port : 8085
           